version: "3"

services:
  client:
    build:
      context: .
      dockerfile: docker/development/nuxt/Dockerfile
    volumes:
      - ./client:/app
      - client_node_modules:/app/node_modules
    ports:
      - 80:8080
    tty: true

  server:
    build:
      context: .
      dockerfile: docker/development/go/Dockerfile
    volumes:
      - ./server:/go/src/github.com/suganuma3510/homeres
    depends_on:
      - db
    ports:
      - "3000:3000"
    tty: true

  db:
    build:
      context: .
      dockerfile: docker/development/mysql/Dockerfile
    volumes:
      - ./db/data:/var/lib/mysql"
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password

volumes:
  client_node_modules:
