version: "3"

services:
  client:
    build:
      context: .
      dockerfile: docker/development/nuxt/Dockerfile
    volumes:
      - ./client:/app
      - client_node_modules:/app/node_modules
    ports:
      - 80:8080
    tty: true

  server:
    build:
      context: .
      dockerfile: docker/development/go/Dockerfile
    volumes:
      - ./server:/go/src/github.com/suganuma3510/homeres
    ports:
      - "3000:3000"
    tty: true

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
      MYSQL_USER: root
      MYSQL_PASSWORD: password

volumes:
  client_node_modules:
  db_data:
