version: 2.1

executors:
  default:
    machine:
      image: circleci/classic:edge

jobs:
  build:
    executor:
      name: default
    steps:
      - checkout
      - run:
          name: docker-compose build
          command: docker-compose build
  test:
    executor:
      name: default
    steps:
      - checkout
      - run:
          name: client test
          command: docker-compose run --rm client yarn test

workflows:
  build-test:
    jobs:
      - build
      - test:
          requires:
            - build
