version: 2.1

executors:
  default:
    machine:
      image: circleci/classic:edge

jobs:
  build:
    executor:
      name: default
    steps:
      - checkout
      - run:
          name: docker-compose build
          command: docker-compose build
      - run:
          name: client test
          command: docker-compose run --rm client yarn test
      - run:
          name: server test
          command: docker-compose run --rm server go test -v ./...

workflows:
  build-test:
    jobs:
      - build
